# start by pulling the python image
FROM python:3.12-bullseye
# create a directory for the app
WORKDIR /app

# copy the requirements file into the image
COPY ./requirements.txt /app/requirements.txt

# install the dependencies and packages in the requirements file
RUN python3 -m pip install --upgrade pip
RUN pip3 install -r requirements.txt

# copy every content from the local file to the image
COPY ./app /app/app

EXPOSE 8000
CMD ["python3", "-m", "app"]